openapi: 3.0.0
info:
  title: Technical Writer Tasks API
  description: API for managing technical writer tasks.
  version: 1.0.0
servers:
  - url: https://api.techwriter.xyz
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Task:
      type: object
      properties:
        task_id:
          type: string
        title:   
          type: string
        description: 
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        component:
          $ref: '#/components/schemas/ComponentEnum'
        connected_tasks:
          type: array
          items:
            $ref: '#/components/schemas/ConnectedTask'
    TaskInput:
      type: object
      required:
       - title
       - description
       - status
       - component
      properties:
        title: 
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        component:
          $ref: '#/components/schemas/ComponentEnum'
        connected_tasks:
          type: array
          items:
            $ref: '#/components/schemas/ConnectedTask'
    ConnectedTask:
      type: object
      properties:
        task_id:
          type: string
        title: 
          type: string
        description: 
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
    StatusEnum:
      type: string
      enum: [OPEN, IN_PROGRESS, COMPLETED]
    ComponentEnum:
      type: string
      enum: [API_DOCS, HELP_CENTER, SDK_DOCS, OAS_FILE]
security:
  - ApiKeyAuth: []
paths:
  /tasks:
    get:
      summary: Retrieve all technical writer tasks.
      operationId: getTasks
      parameters:
        - name: status
          in: query
          description: Filter tasks by status.
          required: false
          schema:
            $ref: '#/components/schemas/StatusEnum'
        - name: component
          in: query
          description: Filter tasks by component.
          required: false
          schema:
            $ref: '#/components/schemas/ComponentEnum'
        - name: updatedAfter
          in: query
          description: Filter tasks that have been updated after a specific date (YYYY-MM-DD).
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: An array of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized, API key missing or invalid.
   /task:
    post:
      summary: Add a new technical writer task.
      operationId: addTask"Document new API endpoint"
     
        requestBody:
         required: true
         content:
         application/json:
         schema:
           $ref: '#/components/schemas/TaskInput'
	   responses:
  	'201':
    	  description: Task successfully created.
    	  content:
            application/json:
              schema:
              type: object
          properties:
            task_id:
              type: string
            message:
              type: string
        '400':
          description: Bad request due to invalid input.
          content:
            application/json:
              schema:
              type: object
          properties:
            error:
              type: string
  '401':
    description: Unauthorized, API key missing or invalid.